databricks/databricks-sql-go

- connection.go
- driver.go
- examples/go.mod
- examples/go.sum
- examples/list/list.go
- examples/tview/tview.go
- go.mod
- hive/client.go
- hive/hive.go
- hive/metadata.go
- hive/operation.go
- hive/result_set.go
- hive/session.go
- rows.go
- statement.go
(moving from arikfr/go-dbsql to databricks/databricks-sql-go)
> Update references to new repo location

- connection.go
- driver.go
- examples/go.mod
- examples/go.sum
- examples/list/list.go
- examples/tview/tview.go
- go.mod
- hive/client.go
- hive/hive.go
- hive/metadata.go
- hive/operation.go
- hive/result_set.go
- hive/session.go
- rows.go
- statement.go
Reverts databricks/databricks-sql-go#3
> Revert "Fix the module name"

- README.md
add preview text the readme file
> add preview to the readme file

- CHANGELOG.md
- CONTRIBUTING.md
- NOTICE
- README.md
- Update README
- Add NOTICE
- Add CONTRIBUTING.md
**Important**: I don't have context on the project layout, formatting, or testing requirements. These are left as **TBD**.
> Polish readme + contributing + licence docs

- driver.go
Update user agent of GoLang client.
> [PECO-163] Update GoLang clients' user agent

- internal/client/client.go
- internal/config/config.go
Adding minimum TLS version to 1.2
Fixing if statement
> Couple of small fixes

- .github/workflows/go.yml
- Makefile
Adding proper Github actions for linting and testing
> Improve Github actions

- .github/workflows/go.yml
It is better to keep dev loop and github actions using the same tooling.
> Using make test in Github actions

- examples/queryrow/main.go
- examples/queryrows/main.go
Updated `res` to pointer in examples/queryrow/main.go
Uncomment row print in examples/queryrows/main.go
Signed-off-by: Tauseef Hussain <tauseef.hussain@databricks.com>
> Minor change to examples

- connection.go
- connector.go
- driver.go
- internal/client/client.go
- internal/config/config.go
- logger/logger.go
- result.go
- rows.go
- statement.go
Adding or revising documentation above public methods.
> Add or edit documentation above methods

- README.md
- doc.go
Adding some tweaks to the readme to clean up the code examples.
> Tweaks to readme

- connection.go
- connection_test.go
If the context is canceled already, we can't use it to close the operation. Create new context with the context data.
> Use new ctx when closing operation after cancel

- doc.go
Tiny catch on what we're saying is default max rows
> Max rows is 100k not 10k

- README.md
Removing information about Beta (as we target GA).
> Remove beta tags in readme

- internal/client/client.go
- internal/client/thriftclient.go
- internal/rows/arrowbased/arrowRows.go
- internal/rows/arrowbased/arrowRows_test.go
- internal/rows/columnbased/columnRows.go
- internal/rows/rows.go
- internal/rows/rows_test.go
- internal/rows/rowscanner/rowScanner.go
- internal/rows/rowscanner/rowscanner_test.go
> update rows to remove thrift

- connection.go
- internal/client/client.go
- internal/client/restclient.go
- internal/client/thriftclient.go
- internal/rows/arrowbased/arrowRows.go
- internal/rows/rows.go
This is hacky code written as the quickest way to get results using the REST API.
> P.O.C. for fetching arrow format results via REST API

- connector.go
- doc.go
- driver_e2e_test.go
- errors/errors.go
- examples/error/main.go
- internal/client/client.go
- internal/config/config.go
- internal/errors/err.go
- internal/errors/err_test.go
- internal/rows/arrowbased/arrowRows.go
- internal/rows/rowscanner/rowScanner.go
- testserver.go
Added IsRetryable and RetryAfter functions to DBError interface.
Added an internal error type for retryable errors.
Updated client to insert a retryable error instance into the error chain.
> Implemented IsRetryable() and RetryAfter() for DatabricksError

- connection.go
- driverctx/ctx.go
- internal/config/config.go
- internal/fetcher/fetcher.go
- internal/rows/arrowbased/arrowRows.go
- internal/rows/arrowbased/batchloader.go
User will be able to define `UseLz4Compression` and the results, either via cloud fetch or arrow batches, will be decompressed.
> Lz4 decompression

- connection.go
- internal/config/config.go
- internal/rows/arrowbased/arrowRows.go
- internal/rows/rows.go
Enables cloud fetch with a couple of bug fixes and with user-defined connector parameter.
Please check each commit for more information on the steps took to get the initial cloud fetch work to an executable state.
> Enable cloud fetch e2e

- examples/cloudfetch/cloudfetch_test.go
- internal/fetcher/fetcher_test.go
- internal/rows/arrowbased/arrowRows.go
- internal/rows/arrowbased/batchloader.go
- internal/rows/arrowbased/batchloader_test.go
- internal/rows/arrowbased/errors.go
Unit and end-to-end tests:
- batchloader_test.go (unit)
- test cloud fetch happy case where the server returns arrow batch bytes
- test cloud fetch sad case where the server status code is 500
- fetcher_test.go (unit)
- test concurrent fetcher with mock fetchable items to check if results are expected and whether the fetcher took the estimated amount of time
- cloudfetch_test.go (e2e)
- test end to end functionality of cloud fetch by comparing actual results from execution with and without cloud fetch
> Cloud Fetch tests

- .github/CODEOWNERS
> Bye Matthew

- parameter_test.go
- parameters.go
We need to dynamically set the actual values of decimals, and this should be the smallest value that could hypothetically encompass the decimal string.
> [PECO-1112] Added decimal handling

- doc.go
We need to update the doc to teach users how to use these features.
> [PECO-1124] Update the docs for Go for Parameterized Queries and Staging Ingestion

- doc.go
- examples/arrrowbatches/main.go
Updated the example and documentation for GetArrowBatches to include releasing the arrow batch.
> Updated example and docs for GetArrowBatches

- auth/oauth/oauth.go
- auth/oauth/u2m/authenticator.go
- examples/oauth/main.go
Added the GCP cloud type (i.e. domain .gcp.databricks.com) to OAuth implementation.
> Added GCP cloud type for OAuth

- auth/oauth/m2m/m2m.go
> Remove secrets

- connection.go
- doc.go
- errors/errors.go
- examples/parameters/main.go
- parameter_test.go
- parameters.go
[PECO-1962]
Replaces databricks/databricks-sql-go#232
[PECO-1962]: https://databricks.atlassian.net/browse/PECO-1962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PECO-1962] Support positional query parameters

- CHANGELOG.md
- driver.go
> Prepare for v1.9.0 release
