- connection.go
- escaper.go
- escaper_test.go
- statement.go
- statement_test.go
In the current implementation, the query
```sql
SELECT *
FROM table_name
WHERE string_column = ?;
```
with arg list `[]any{"a'b'c"}` will be translated into the following invalid query string:
```sql
SELECT *
FROM table_name
WHERE string_column = a'b'c;
```
This PR escapes string, time and turn the query into:
```sql
SELECT *
FROM table_name
WHERE string_column = 'a''b''c';
```
Referring to how python connector escape strings:
https://github.com/databricks/databricks-sql-connector/blob/a7af04c8a0df274b443fcc5ca6b40457019ab5ce/src/databricks/sql/utils.py#L126
> Escape Parameters

- README.md
We use this approach on the Python and Node README's.
> Make example DSN easier to read

- CHANGELOG.md
- README.md
- connection_test.go
- hive/result_set.go
Apache Hive thrift always sends `HasMoreResults==false` even when more results are available. This change updates the Next() method to continue fetching pages of results until an empty page is received.
This quirk of behaviour also affects the [Databricks NodeJS connector](https://github.com/databricks/databricks-sql-nodejs/issues/21) and we work around it in a similar way there.
> Fix: FetchResults truncates rows returned by the server

- .github/workflows/dco-check.yml
- CONTRIBUTING.md
Mirrors the changes to [NodeJS](https://github.com/databricks/databricks-sql-nodejs/pull/49) and [Python](https://github.com/databricks/databricks-sql-python/pull/13) connectors.
> [PECO-247] Add DCO Check

- databricks.go
- driver.go
- driver_test.go
Provide clients a way to override the `clientId` (user-agent suffix) and `godatabrickssqlconnector` version in the user agent
Ran `list.go` example on IDE with `DATABRICKS_DSN=databricks://:dapie80c33546da149a3ea2876f35b32e644@e2-demo-west.cloud.databricks.com/sql/1.0/endpoints/77d7dabbececf7ca?clientId=go-dbsql` env var:
```
GOROOT=/opt/homebrew/Cellar/go/1.19/libexec #gosetup
GOPATH=/Users/matthew.kim/go #gosetup
/opt/homebrew/Cellar/go/1.19/libexec/bin/go build -o /private/var/folders/01/yq3bj65n38x_t6q8wbdc0xj00000gp/T/GoLand/___go_build_github_com_databricks_databricks_sql_go_examples_list github.com/databricks/databricks-sql-go/examples/list #gosetup
/private/var/folders/01/yq3bj65n38x_t6q8wbdc0xj00000gp/T/GoLand/___go_build_github_com_databricks_databricks_sql_go_examples_list …
```
> [PECO-270] allow clients to provide client info in user agent

- escaper.go
- escaper_test.go
- statement.go
- statement_test.go
Since release v0.1.3, When running `examples/list/list.go`, the `SHOW TABLES IN @p1` queries were all failing with messages like these:
```
2022/09/09 19:16:14 error in querying database 000_demo_db: Error running query: [PARSE_SYNTAX_ERROR] org.apache.spark.sql.catalyst.parser.ParseException: 
[PARSE_SYNTAX_ERROR] Syntax error at or near ''000_demo_db''(line 1, pos 15)
== SQL ==
SHOW TABLES IN '000_demo_db'
---------------^^^
```
After this change, these examples work as it had before release v0.1.3:
```
2022/09/09 19:18:58 Tables in 000_demo_db:
2022/09/09 19:18:58   bi0_mbpartner
```
> [PECO-306] bug fix for escape characters breaking E2E examples

- hive/operation.go
Supports cancel operation (e.g. for long-running queries)
Modified `statement.go: 149 (func exec)` to Cancel instead of Close and tested via IDE
When manually overriding `session.ExecuteStatement` to RunAsync: true in code and running the above query, able to confirm that cancel operation work as intended and cancels the query execution.
`session.ExecuteStatement` (`s.hive.client.ExecuteStatement`) appears to work synchronously because the SDK will not return a response until the query is fully executed. I was unable to test cancellation while query was executing, only the cancellation before FetchResults
> [PECO-271] Support cancel operation

- rows.go
- rows_test.go
- testserver.go
Implement fetching result set rows in pages both with and without direct results. Handle skipped result pages, seeking past result set, and seeking before start of result set. Fixed Rows.Columns to correctly use metadata from direct results. Added unit tests for the rows structure.
> Implement fetching result set rows in pages

- connection.go
- connector.go
- driver_e2e_test.go
- examples/queryrows/main.go
- internal/client/client.go
- internal/config/config.go
- internal/sentinel/sentinel.go
- internal/utils.go
Implementing Ping and Close methods in connection.
Added support for catalog and schema definition:
```go
func WithInitialNamespace(catalog, schema string) connOption {
return func(c *config.Config) {
if catalog != "" {
c.Catalog = &catalog
}
if schema != "" {
c.Schema = &schema
}
}
}
```
> implementing ping, close. Add namespace support

- connection.go
- connector.go
- driver.go
- examples/timezone/main.go
- internal/client/client.go
- internal/sentinel/sentinel.go
- internal/utils.go
- logger/logger.go
- utils/logger.go
Adding a logger package that is exposed publicly so our users can set log levels and output writers.
Levels can be set by using `DATABRICKS_LOG_LEVEL` environment variable or calling `SetLogLevel`
```go
if err := dbsqllog.SetLogLevel("info"); err != nil {
log.Println(err)
}
```
> Configurable logging

- connection.go
- connection_test.go
- internal/client/test_client.go
- rows_test.go
Created unit tests comprehensively covering branching logic for private functions in `connection.go` (`runQuery`, `executeStatement`, `pollOperation`) and connection methods (`ExecContext`, `QueryContext`)
> Tests for connection.go (ExecContext, QueryContext)

- connection.go
- internal/config/config.go
- internal/config/config_test.go
Adding location property to config of type `time.Location` so session param timezone can be used to parse dates and timestamps. 
> adding location to user config

- connection.go
- connection_test.go
- statement.go
Increasing code coverage in connection.go to account for not supported methods.
Will add code coverage for Close() in a separate PR.
> Increasing code coverage in connection.go

- connection_test.go
- connector_test.go
- internal/config/config.go
- rows_test.go
- statement_test.go
Increased coverage via unit tests to 89.1% with tests added for `statement.go`, `connector.go`
> Increased coverage to statement and connector

- internal/client/client.go
`thrift.NewTHttpClientWithOptions` may return an error, in which case `tTrans` is `nil`, which causes the next line to panic with the message `interface conversion: thrift.TTransport is nil, not *thrift.THttpClient` on the next line.
Signed-off-by: Eric Bannatyne <eric@sigmacomputing.com>
> Don't ignore error in InitThriftClient

- connection.go
- rows.go
- rows_test.go
When a query returns direct results it is possible that all the query result rows are contained therein.  In this case the server can automatically close the operation.  This is indicated by a non-null CloseOperation member in the TSparkDirectResults structure. In this case calls to Rows.Close don't require any interaction with the server as the operation is already closed.
- added a NewRows function and updated connection to use it when creating Rows
- added logic in NewRows to check for an already closed operation
- updated Rows.Close so we don't make a server round trip when not necessary
- added a unit test for the close optimization logic
> Close optimization for Rows

- connection.go
- connection_test.go
- examples/createdrop/main.go
- examples/workflow/main.go
When executing a query there is a rows object returned to the client and the client is then responsible for closing the row set when finished with it.  
Closing the rows causes the driver to close the operation on the server.
When executing a statement (ex. DROP TABLE ...) the client doesn't receive anything by which they can close the operation.  This results in an operation that is completed but not closed.  Eventually the open operation is closed due to inactivity but the driver should be closing the operation.
- updated connection.ExecContext to close the operation if 1) we receive an operation handle back from the server and 2) the operations status is not already closed.
- added unit test to check that we do/don't close the operation depending on the returned operation status. …
> Close operation after executing statement

- rows.go
- rows_test.go
time.Time can represent dates with a negative year, however the time.ParseInLocation function does not handle parsing date strings with a negative year.
- Added our own parseInLocation function which handles parsing with negative years.
- Added unit tests for date/time parsing.
> Handle parsing negative years in dates

- CHANGELOG.md
- connector.go
- connector_test.go
- driver.go
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/databricks/databricks-sql-go/pull/74).
* __->__ #74
fix thread safety issue
This fixes a thread safety (and structural issue) with connector. Because connectors have a long lifetime (potentially process-lifetime), and are used by multiple threads it's not safe to share the same thrift client connection.
This changes the connector so that a new thrift client is created on each connection. The go DB library will perform pooling of connections, so we don't need to worry about it here.
Signed-off-by: Carl Verge <carl.verge@databricks.com>
> fix thread safety issue

- doc.go
Documentation in Go package docs so that they will appear in https://pkg.go.dev/github.com/databricks/databricks-sql-go. Sections include:
- Usage
- Connection via DSN string
- Connection via connector object
- Query cancellation, timeout
- CorrelationId and ConnId
- Logging
> Package doc (doc.go)

- connection.go
- connection_test.go
There were a few cases where we were not returning the correct AffectedRows in the result. Silly mistake.
> Fix for result.AffectedRows

- connector_test.go
- internal/config/config.go
For https connections (the case in production), we always use port 443, so set that as default.
> Set default port to 443

- .github/workflows/go.yml
- Makefile
- connection_test.go
- driver_e2e_test.go
- internal/sentinel/sentinel.go
- internal/sentinel/sentinel_test.go
Because we were spanning a new coroutine to cancel the request, the connection was closing and in parallel the sentinel was trying to cancel
In http_client the coroutines were racing to closeResponse
This PR fixes the issue and adds a new action to run race condition tests.
> Fixing cancel race condition

- connector.go
- connector_test.go
- driver.go
- driver_test.go
- internal/config/config.go
In this PR, we update the driver version to 1.0.1 to reflect the latest cut. We also move the DriverVersion to a more visible const in `driver.go`. 
(Already merged) Most of the code in `driver.go:Open` is the same as `driver.go:OpenConnector` so these are merged.
> Update DriverVersion in Config to 1.0.1

- connector.go
- testdata/OpenSessionSuccess.json
Our thrift server does not actually honour ClientProtocol. We have to use ClientProtocolI64.
> use ClientProtocolI64

- driver_e2e_test.go
- internal/client/client.go
- internal/config/config.go
- internal/config/config_test.go
- testserver.go
Be more restrictive on retries: only retry on 429 and 503 StatusCodes or connection errors.
Return better error messages regarding retry reasons and invalid user input.
> Improve error message and retry behaviour

- internal/client/client.go
- internal/client/client_test.go
- internal/rows/rows_test.go
- testserver.go
- retry on 500 status codes if the server operation is idempotent
- retry on request errors except: too many redirects, invalid protocol scheme,  TLS cert verification failure
> Updated retry behaviour

- internal/rows/arrowbased/arrowRows.go
- internal/rows/arrowbased/arrowRows_test.go
- internal/rows/arrowbased/columnValues.go
- internal/rows/arrowbased/testdata/nullsInComplexTypes.json
Github issue #126 https://github.com/databricks/databricks-sql-go/issues/126 
Null member values in complex types (i.e. array, map, and struct) were being scanned as the zero value of the member type.
Updated column value containers for complex types to generate correct JSON for null member values. 
In cases where no type can be determined for a member an error was being thrown for an unhandled data type.
For example in the query "select map('red', NULL, 'green', NULL) as sample_map" there is no determined type for the map values. 
Added a new column value container to be created to correspond to the arrow NullType.
Updated expected values in existing list test now that null elements are no longer being treated as the zero-value of the type.
Added a new test for the case where the type of …
> Bug fix for null values in complex types

- driver.go
version 1.3.0:
Updated the retry behaviour to retry on a wider range of errors and results if the server operation is idempotent.
Bug fix for issue where complex types with a null property were not being handled correctly.
Allow for user provided authenticator.
> Bump version to 1.3.0

- internal/rows/arrowbased/arrowRows.go
- internal/rows/arrowbased/arrowRows_test.go
- internal/rows/arrowbased/testdata/queryVExec.json
When executing a statement that doesn't produce rows (ex. CREATE TABLE ....) using DB.Query() instead of DB.Exec() the driver would panic. When DB.Query() is used we try to create a row object.  In this case there was a mismatch in the schema metadata returned by thrift and the arrow schema metadata. The thrift schema was indicating a single column named 'Result' while the arrow schema metadata was indicating no columns. Moved the code creating the arrow schema and column info into separate functions. Updated creation of the column info to handle mismatch between the arrow and thrift schemas.  
> Bug fix for query that doesn't produce rows

- CHANGELOG.md
- driver.go
- Update version and changelog
- 1.3.1 contains a bug fix for queries that don't produce a result set
> Bump version to 1.3.1

- connection.go
- connection_test.go
- errors/errors.go
When a query terminated in either an unknown or an unexpected operation state the connection was creating a driver error with a static message. 
Updated to include the operation state in the error message for an unknown operation state situation. 
Updated the case of an unexpected operation state to include the state and the operation status display message. 
Updated unit tests based on the new error message.
> Improve error information when query terminates in unexpected state.

- connector.go
- connector_test.go
- internal/client/client.go
- internal/config/config.go
This change enables passing a RoundTripper as a configuration parameter (via the WithTransport() func) to use, for instance, a Socks5 proxy.
If the transport is not configured, it remains with the original behavior. 
- Changed Transport.Base to be of interface `http.RoundTripper` (is returned as that at `PooledTransport()` ) 
- Added 'WithTransport()' func to set the transport configuration. 
- Added validation to existing test case.
> Enable Transport configuration for http client

- doc.go
Added an example to doc.go showing how to register callbacks in the query context to retrieve the connection and query Id.
> Updated doc.go for retrieving query id and connection id

- connection.go
- errors/errors.go
- internal/config/config.go
- internal/rows/arrowbased/batchloader.go
Throw error for expired cloud fetch links. For now, no special handling or retries.
> Cloudfetch expired links

- internal/rows/arrowbased/arrowRows_test.go
- internal/rows/arrowbased/columnValues.go
- internal/rows/arrowbased/testdata/issue147.json
Issue with reading a table with a MAP column, but only when the table was created by copying an existing table. The bug was caused by an indexing issue when reading map values from an arrow batch.  The occurrence of the bug was dependent on the configuration of batches the result set was broken down into. Added a new test using the arrow batch returned in the error scenario.  Also fixed an existing test that had been masking this bug.
> Bug fix issue 147: BUG with reading table that contains copied map

- connector.go
- connector_test.go
- doc.go
Updated WithServerHostname to allow prefixing the hostname with 'https:' or 'http:' to specify which protocol to use. Github issue #140
> Allow WithServerHostname to specify protocol

- connection.go
- internal/cli_service/README.md
- internal/cli_service/cli_service-consts.go
- internal/cli_service/cli_service.go
- internal/config/config.go
Updated thrift client code to latest version.
Added support for named query parameters.
Not yet complete.  The correct sql type needs to be set in TSparkParameter struct.  Need to add support for date/time and intervals.
> Named parameter support and update Thrift

- connection.go
- errors/errors.go
- parameter_test.go
- parameters.go
- statement_test.go
In this PR, we add further handling to allow for special types to be set via the DBSQLParams variable.
> [PECO-1016-2] Add handling for special types

- internal/rows/arrowbased/arrowRows.go
- internal/rows/rows.go
Fixed use of defer in a for loop in arrow row scanner.  Also setting reference to raw arrow batch bytes to nil after reading batch. Updated rows to close it's row scanner before fetching a result page from the back end.
> Reduce driver memory usage

- internal/fetcher/fetcher.go
- internal/fetcher/fetcher_test.go
- internal/rows/arrowbased/arrowRows.go
- internal/rows/arrowbased/arrowRows_test.go
- internal/rows/arrowbased/batchloader.go
- internal/rows/arrowbased/batchloader_test.go
- internal/rows/columnbased/columnRows.go
- internal/rows/errors.go
- internal/rows/rows.go
- internal/rows/rows_test.go
- internal/rows/rowscanner/resultPageIterator.go
- internal/rows/rowscanner/resultPageIterator_test.go
- internal/rows/rowscanner/rowScanner.go
- internal/rows/rowscanner/rowscanner_test.go
Step one of exposing arrow batches directly to users. 
Moved the logic for iterating over the pages in a result set into ResultPageIterator.  
Rows now composes in ResultPageIterator. 
Introduced Delimeter type. Delimeter tracks a start/end point and provides functions for determining if a point is within the delimiter range and the direction of the point if it is outside the delimeter range. 
Updated sparkArrowBatch, arrowRowScanner, columnRows, rows to use Delimiter. 
Updated the Fetch logic for cloudURL and localBatch so that the concurrentFetcher doesn't need to hold or pass through a Config instance.
> PECO-1054 Expose Arrow batches to users

- .github/workflows/go.yml
- go.mod
We need to change the version that we have in our Github action and bump the requirements in the go registry. (May also need to do major version change)
> [PECO-1116] Change version of GO being used in Github Action

- connection.go
- examples/parameters/main.go
- parameter_test.go
- parameters.go
We don't currently have an example for parameterized queries, we should add one.
> [PECO-1048] Add example for parameterized queries

- connection.go
- connection_test.go
- driverctx/ctx.go
- internal/client/client.go
- internal/fetcher/fetcher.go
- internal/sentinel/sentinel.go
Differentiated some cases where the logged messages were ambiguous as to which code path they came from. 
Updated client to be more consistent in what context information is included in logging messages. Also updated client methods to produce a duration log message even if there is an error.  Updated error handling to log the wrapped error message.
> Logging improvements

- connection.go
Earlier when I had coded this, I accidentally introduced a bug where the user facing API was delete instead of remove. This was because under the hood we are doing a delete operation. This should fix the bug, we should definitely hotfix our release. I've tested it locally for each operation this time.
> [PECO-1179] Added handling for staging remove

- auth/oauth/m2m/m2m.go
- auth/oauth/m2m/m2m_test.go
- auth/oauth/oauth.go
- auth/oauth/u2m/authenticator.go
- driverctx/ctx.go
Updated m2m authenticator to use "all-apis" scope.
Added a new constructor function for m2m authenticator that allows client to pass in additional scopes.
> Bug fix for OAuth m2m scopes

- internal/rows/arrowbased/arrowRecordIterator.go
- internal/rows/rows_test.go
- internal/rows/rowscanner/resultPageIterator.go
- internal/rows/testdata/zeroRows/zeroRowsDirectResults.json
- internal/rows/testdata/zeroRows/zeroRowsFetchResult.json
Bug fix: The HasNext() function for Go driver arrow record iterator returning EOF for empty result set.
Essentially, the HasNext() logic was assuming there were records in the result set in the case that the original return from executing the statement didn't specify, or if there were no direct results.
Updated arrowRecordIterator.HasNext() to check state of underlying iterators. This handles the case of direct results that contain no records. 
Updated resultPageIterator.HasNext() to try fetching a result page if necessary to determine if there are more records.
Added tests for empty result sets with direct results enabled and disabled.
Internal ticket: [ES-975398]
[ES-975398]: https://databricks.atlassian.net/browse/ES-975398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …
> Bug fix: The HasNext() function for Go driver arrow record iterator returning EOF for empty result set.

- connection.go
Customers have reached out in Node and GO about protocol versioning not being correctly reflected by the server. We've decided to revert these changes in Node, this PR does the same for GO.
> [PECO-1356] Removed protocol check in GO

- connection.go
`os.ReadFile` reads all of the content of the file into a byte array in memory, which can cause memory consumption pressure for users. Instead, an `os.File` instance is itself a byte reader, and we can provide the file directly to `http.NewRequest` so it can read the file in chunks and upload it as a stream, thus not holding the whole file in memory.
> staging put: stream file uploads instead of loading all to memory

- connection.go
> fix: Don't panic on `remove` op

- CHANGELOG.md
- driver_e2e_test.go
- parameter_test.go
- parameters.go
> Fix formatting of *float64 parameters

- connection.go
Closes https://github.com/databricks/databricks-sql-go/issues/211
Instead of https://github.com/databricks/databricks-sql-go/pull/212
> hotfix: Provide content length on file put

- connector.go
- connector_test.go
- internal/client/client.go
The driver cannot connect to the workspace whose hostname is an internal private link hostname, this is because its domain is not added into Databricks workspace certificate.  See https://github.com/databricks/databricks-sql-go/issues/223
This change adds connection option `WithSkipTLSHostVerify` which can disable verifying the hostname in the server certificate. In this mode, TLS is susceptible to machine-in-the-middle attacks. Please only use this option when the hostname is an internal private link hostname. 
Here is the usage
```go
connector, err := dbsql.NewConnector(
dbsql.WithServerHostname("<hostname>"),
dbsql.WithHTTPPath("<http_path>"),
dbsql.WithAccessToken("<token>"),
dbsql.WithSkipTLSHostVerify(),
)
```
> Add connection option WithSkipTLSHostVerify for privatelink host

- connector.go
Fixes: https://github.com/databricks/databricks-sql-go/issues/201
That way we can programmatically add arguments to the `NewConnector` function instead of copy/pasting all of them across conditionals.
> Expose dbsql.connOption type

- connector.go
Follow up on databricks/databricks-sql-go#202
> Fix missed connOption when exporting ConnOption type

- internal/client/client.go
Fixes https://github.com/databricks/databricks-sql-go/issues/242
Fixes https://github.com/databricks/databricks-sql-go/issues/231
This needs to actually pass ctx so custom authenticators can make use of the context.
> pass ctx properly in internal client.ExecuteStatement

- internal/rows/arrowbased/batchloader.go
- internal/rows/arrowbased/batchloader_test.go
When file encryption is enabled with customer provided keys (SSE-CPK), we must pass the keys in HTTP headers in the fetch request. These headers are provided in the property `httpHeaders` in the `TSparkArrowResultLink`
> [PECO-2050] Add custom auth headers into cloud fetch request

- connector_test.go
- internal/config/config.go
Enable cloud fetch (EXTERNAL_LINKS) by default. 
Benchmark tests
Following table demonstrates the improvement in execution times for large queries.
| test_case | percent_reduction |
|-----------|------------------|
| large_results_2050mb | 56.58973580321896 |
| large_results_1025mb | 51.78689883913764 |
| large_results_0500mb | 47.729468599033815 |
| large_results_0100mb | 40.57221647707687 |
| large_results_0250mb | 38.71932974266906 |
| large_results_0050mb | 19.751809720785936 |
| large_results_0025mb | -7.421625079974409 |
| large_results_0010mb | -7.752808988764046 |
| large_results_0005mb | -36.91376701966717 |
We get **~57%** deduction in large queries execution time. 
For result size > 4.1GB, we cannot even fetch without cloud fetch with default spark configs.
Ref error: `ERR …
> enable cloud fetch by default

- connection.go
- connection_test.go
- connector.go
- internal/client/client.go
- internal/client/testclient.go
- internal/config/config_test.go
- internal/thrift_protocol/protocol_feature_util.go
- internal/thrift_protocol/protocol_feature_util_test.go
This PR introduces changes to handle thrift protocol version returned in TOpenSessionResp for supporting different features like cloud fetch, compression, parameterized queries.
* [`connection.go`](diffhunk://#diff-25a7cf08cc8fc8eb57475835cc380524de2fd1215cda9c6915132ae86dbd80a7L288-R312): Added checks for server protocol version to conditionally support features such as direct results, LZ4 compression, cloud fetch, Arrow format, and parameterized queries. [[1]](diffhunk://#diff-25a7cf08cc8fc8eb57475835cc380524de2fd1215cda9c6915132ae86dbd80a7L288-R312) [[2]](diffhunk://#diff-25a7cf08cc8fc8eb57475835cc380524de2fd1215cda9c6915132ae86dbd80a7L305-R324)
* [`internal/thrift_protocol/protocol_feature_util.go`](diffhunk://#diff-6d5ab0961a6f4e5eee4a29f813d12b51e54f5f45ccaed7360eb6a685e193a1a4R1-R48 …
> [PECOBLR-314] handle thrift protocol version

- CHANGELOG.md
- README.md
- doc.go
- driver.go
Prepare for the next release of go driver (1.7.0) which adds the following changes:
- Enable cloud fetch mode by default (databricks/databricks-sql-go#260)
- Handle thrift protocol version for conditional feature support (direct results, LZ4 compression, Arrow support, parameterized queries) (databricks/databricks-sql-go#261)
> prepare release v1.7.0

- connection.go
- connection_test.go
Older DBR versions (< 12) did not contain the isStagingOperation field causing a seg fault due to nil values, we gracefully handle older DBRs 
Fixes #265
> Add nil handling for isStagingOperation to handle older DBR versions

- internal/cli_service/cli_service.go
- Update thrift client library after cleaning up unused fields and structs. 
- Certain fields are removed as they might be deprecated/removed/change in the future.
- Added server protocol version SPARK_CLI_SERVICE_PROTOCOL_V9
- Tested using e2e and unit tests
> [PECOBLR-402] Update thrift client library after cleaning up unused fields and structs

- internal/rows/arrowbased/arrowRecordIterator.go
- internal/rows/arrowbased/arrowRecordIterator_test.go
- rows/rows.go
Allow ability to get the arrow schema when fetching Arrow Batches.
Currently, the GetArrowBatches(ctx) method in the DBSQL driver does not expose schema information, this PR adds support to get Schema directly like the Arrow Flight interface.
> Add schema to ArrowBatchIterator

- examples/ipcstreams/main.go
- internal/rows/arrowbased/arrowIPCStreamIterator.go
- internal/rows/arrowbased/arrowRows.go
- internal/rows/arrowbased/arrowRows_test.go
- internal/rows/arrowbased/batchloader.go
- internal/rows/arrowbased/batchloader_test.go
- internal/rows/columnbased/columnRows.go
- internal/rows/rows.go
- internal/rows/rowscanner/rowScanner.go
- rows/rows.go
This PR adds support for accessing raw Arrow IPC (Inter-Process Communication) streams
directly, providing an alternative to the existing parsed Arrow record interface. This
allows users to work with the Arrow binary format without the overhead of parsing,
enabling use cases like streaming data to other systems or custom processing pipelines.
- **Refactored internal batch iterator** to expose IPC streams:
- Renamed `BatchIterator` → `IPCStreamIterator` (returns `io.Reader`)
- Updated implementations to return raw IPC streams instead of parsed batches
- Created backward-compatible `BatchIterator` wrapper
- **Added public API** in `rows` package:
- New `GetArrowIPCStreams()` method on `Rows` interface
- New `ArrowIPCStreamIterator` interface with methods:
- `Next() (io.Reader, error)` - …
> Add Arrow IPC stream iterator for direct access to Arrow buffer

- .gitignore
- connector.go
- examples/query_tags/main.go
- internal/config/config_test.go
This PR **refactors session parameter handling** in the Go SQL Connector to align with other Databricks drivers (Java, Python). Previously, session parameters were set using `SET` statements after connection establishment, which was inefficient and inconsistent with other drivers. This new implementation also supports usage of QUERY_TAGS session parameter. Query Tags allow users to attach key-value pairs to SQL executions that appear in the `system.query.history` table.
1. **Refactored Session Parameter Flow** (`connector.go`):
- **Before**: Session parameters were sent via `SET` statements after `OpenSession`
- **After**: Session parameters are passed directly to `TOpenSessionReq.Configuration` during session creation
- **Benefit**: Aligns with Java and Python drivers, and improves …
> [PECOBLR-676] passing session params in open session request instead of SET commands
